baseurl = "https://localhost/"
title = "biologische tuingroep De Ark"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "nl"

# number of words of summarized post content (default 70)
summaryLength = 10

# Define the number of posts per page
paginate = 4 

# not pluralize title pages by default
pluralizelisttitles = false

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
#Shortname = "devcows"
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[menu]

# Main menu
[[menu.main]]
    name       = "home"
    identifier = "menu.home"
    url        = "/"
    weight     = 10

[[menu.main]]
    name       = "over De Ark"
    identifier = "menu.over_de_ark"
    url        = "/over-De-Ark/"
    weight     = 20

#[[menu.main]]
#    name       = "dit is een submenu optie onder Home"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.home"

[[menu.main]]
    name       = "foto's & video's"
    identifier = "menu.fotos"
    url        = "/fotos_en_videos/"
    weight     = 30

[[menu.main]]
    name       = "reglement"
    identifier = "menu.reglement"
    url        = "/huishoudelijk_reglement/"
    weight     = 60

[[menu.main]]
    name       = "werkdagen"
    identifier = "menu.werkdagen"
    url        = "/werkdagen/"
    weight     = 50

[[menu.main]]
    name       = "Berichten"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 40

[[menu.main]]
    identifier = "menu.contact"
    name       = "contact"
    url        = "/contact/"
    weight     = 70


# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "Phone"
#    url = "tel:+12 34 567 89 01"
#    pre = "<i class='fas fa-2x fa-phone'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "GitHub"
#    url = "https://github.com/devcows/"
#    pre = "<i class='fab fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

#[[menu.topbar]]
#    weight = 4
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fab fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#    weight = 5
#    name = "Email"
#    url = "mailto:hello@universal.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Leo Mekenkamp"
    defaultKeywords = ['biologische tuingroep De Ark', 'biologisch tuinieren', 'moestuin', 'volkstuin', 'Nieuw-West', 'duurzaam']
    mainSections = ["blog"]
    defaultDescription = "biologisch tuinieren in Amsterdam Nieuw-West"

    # Social media
#    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
#    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyDXuVVsD6lkI_UJkTuFLjPq1QDbkT9eSpc"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the  form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the  form by entering your Formspree.io endpoint url
#    formspree_action = "https://formspree.io/sample/of/endpoint"
#    _form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your  page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>We zijn een enthousiaste groep van tuinders die in Amsterdam Nieuw-West op duurzaam biologische wijze onze groenten en fruit kweken.</p>"
    copyright = "Copyright (c) 2024, Tuingroep De Ark"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "bio tuingroep De Ark"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    _url = "/"
    address = """<p class="text-uppercase"><strong>tuingroep De Ark</strong>
        <br>Nico Broekhuysenweg 7
        <br>1067 HT&nbsp;&nbsp;Amsterdam
        <br>Nederland
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false 
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 3
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4 
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false 
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "recente berichten"
    subtitle = "Wat gebeurt er zoal op een biologische tuingroep?"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
